### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by viro23** [sidewinder94/GWvW_Overlay#7]
yo, since the new update for that logitech overlay stoped working for me. im getting this msg:

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: gwvw_overlay.exe
  Problem Signature 02: 0.4.12.0
  Problem Signature 03: 55f4bc28
  Problem Signature 04: Logitech-LED
  Problem Signature 05: 1.0.0.0
  Problem Signature 06: 55f4bc27
  Problem Signature 07: 15
  Problem Signature 08: 15
  Problem Signature 09: Logitech_LED.LedNotInitialized
  OS Version:   6.1.7601.2.1.0.256.1
  Locale ID:    1050
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

im not a programer and not shure what that is but would be great if u could fix it. 

thx

**Comment by sidewinder94** [comment]
OK, i thought i had already solved the problem

Working on it

**Comment by sidewinder94** [comment]
I corrected the problem and tested it on a computer that didn't have the keyboard connected, seems resolved.

Could you try to relaunch the application ? 

It should update itself

Please tell me if it solved the problem for you so that i can close the issue

**Comment by viro23** [comment]
Yeah it works, sry it was my bad. It crashed befor it had the chance to
update so i downloaded fresh version and instaled it so its all good. btw
thx for working so much on it, its the best overlay i tried.

On 19 September 2015 at 13:54, Antoine-Ali Zarrouk <notifications@github.com

**Comment by sidewinder94** [comment]
Well i just updated it :)

Obvious it would update :p

Thanks for the feedback :)
